//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItBit.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sexo
    {
        public int SexoId { get; set; }
        public string Descricao { get; set; }
    }
}
